### ISSUE TITLE
is it possible that you can provide a sample just like U2020?

### ISSUE THREAD

**Issue by machinezhou** [gk5885/dagger-android-sample#1]
hi sir, 
I have already got the basic idea of dagger 2, and I know it is different with dagger/square. I've seen your video and document of dagger2, but I really don't know how to use it in my real project. When I study dagger/square, there's a project U2020 for us and I can get a lot of thing through reading the source code. I don know if I express well.
In a word, eh is it possible that you can provide a sample just like U2020? Thank you!

**Comment by ishawnthye** [comment]
Hi machibezhou, do you manage to find an application like u2020 with dagger2??
